import express from 'express';
import { handler as ssrHandler } from './dist/server/entry.mjs';
import process from 'node:process';

// eslint-disable-next-line turbo/no-undeclared-env-vars
const PORT = process.env["PORT"] ?? 8080;

const app = express();
// Change this based on your astro.config.mjs, `base` option.
// They should match. The default value is "/".
const base = '/';

// Cache control middleware
app.use((req, res, next) => { 
  /**
   * The content under `/_astro/` is generated by Astro, their name contains a timestamp of the build, 
   * so we can safely cache them for a long time (1 year) and mark them as immutable.
   * 
   * They will change their name on each build, so we don't have to worry about stale cache.
   */
  if (req.path.startsWith('/_astro/')) {
    res.set('Cache-Control', 'public, max-age=31536000, immutable');
    return next();
  }
  
  if (req.path.startsWith('/api/')) {
    res.set('Cache-Control', 'public, s-maxage=60, max-age=0');
    return next();
  }
  
  // HTML pages
  res.set('Cache-Control', 'public, max-age=3600, must-revalidate');
  return next();
});

app.use(base, express.static('dist/client/'));
app.use(ssrHandler);

app.listen(PORT, () => {
  // eslint-disable-next-line no-undef
  console.log(`Server is running on port ${PORT}`);
});